MONAPP/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'', include('authentication.urls')),
    path(r'map/', include('map.urls')),
    path(r'child/', include('child.urls')),
    path(r'rest/', include('rest_api.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.conf.urls import url
from . import views

app_name="authentication"

urlpatterns = [
    url(r'^$', views.Profile.as_view(), name='profile'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^register/$', views.Register.as_view(), name='register')
]

licenta/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path(r'', include('authentication.urls')),
    path(r'map/', include('map.urls')),
    path(r'child/', include('child.urls')),
    path('admin/', admin.site.urls),

]

map/urls.py
from django.conf.urls import url
from . import views

app_name="map"

urlpatterns = [
    url(r'^$', views.Map.as_view(), name='map'),
    url(r'danger_zones/', views.DangerZone.as_view(), name='dangerZone'),
]

authentication/views.py
import json

from django.http import QueryDict, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

from database import models
from MONAPP.settings import SESSION_USER_ID_FIELD_NAME

from datetime import datetime


class Login(View):
    html = 'authentication/login.html'

    def get(self, request):
        if request.session.get(SESSION_USER_ID_FIELD_NAME):
            del request.session[SESSION_USER_ID_FIELD_NAME]
        return render(request, self.html)

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')

        parent = models.Parent.authenticate(username, password)
        if parent:
            parent.login(request)
            return redirect('authentication:profile')
        else:
            return render(request, self.html, context={
                "error": "Invalid username / password."
            })


class Register(View):
    html = 'authentication/register.html'

    def get(self, request):
        if request.session.get(SESSION_USER_ID_FIELD_NAME):
            del request.session[SESSION_USER_ID_FIELD_NAME]
        return render(request, self.html)

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirmation = request.POST.get('confirmation')

        if password != confirmation:
            return render(request, self.html, {'error': 'Confirmation password is different'})

        try:
            models.Parent.objects.create(
                first_name=request.POST.get('fname'),
                last_name=request.POST.get('lname'),
                email=request.POST.get('email'),
                # locality=request.POST.get('locality'),
                # county=request.POST.get('county'),
                phone=request.POST.get('phone'),
                birth_day=datetime.strptime(request.POST.get('bday'), '%d-%m-%Y'),
                # gender=request.POST.get('gender'),
                username=request.POST.get('username'),
                password=request.POST.get('password'),
                image='profile_image/blank_profile_image.png'
            )
        except Exception as e:
            return render(request, self.html, {'error': e})
        else:
            parent = models.Parent.authenticate(username, password)
            if parent:
                parent.login(request)
                return redirect('authentication:profile')
            else:
                return render(request, self.html, context={
                    "error": "Something went wrong!"
                })


class Profile(View):
    @staticmethod
    def decode(device):
        if device.activated:
            return "Activated"
        return "Not Activated"

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super(Profile, self).dispatch(*args, **kwargs)

    def get(self, request):
        logged_user = request.session.get(SESSION_USER_ID_FIELD_NAME)
        if logged_user:
            return self.profile(request, logged_user)
        else:
            return self.home(request)

    @classmethod
    def profile(cls, request, logged_user):
        notifications = cls.get_notifications(logged_user)
        parent = models.Parent.objects.filter(pk=logged_user).first()
        kids = models.Child.objects.filter(parent=parent)
        grouped = []
        for child in kids:
            device = models.Device.objects.filter(child=child).first()
            apps = models.Applications.objects.filter(device=device)
            if apps:
                # apps = eval(apps.first().app_list)
                apps = eval(apps.first().app_list)
            else:
                apps = [None]
            grouped.append([child, device, cls.decode(device), apps])

        return render(request, "authentication/profile.html", context={
            'notifications': notifications,
            'user': parent,
            'grouped': grouped,
        })

    @staticmethod
    def get_notifications(logged_user):
        return list(models.Notification.objects.filter(parent=logged_user, read=False))

    def post(self, request):
        pass

    def put(self, request):
        put = QueryDict(request.body)

        pk = put.get('pk')

        notification = models.Notification.objects.get(pk=pk)
        notification.read = True
        notification.save()

        return JsonResponse({
            'error': ''
        })

    @classmethod
    def home(cls, request):
        return render(request, "authentication/home.html")

authentication/templates/authentication/base.html
{% load staticfiles %}
<head>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script>
	    $(document).ready(function() {
	        var csrftoken = Cookies.get('csrftoken');
	        function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

			$('.dropdown-button').dropdown({
				  inDuration: 300,
				  outDuration: 225,
				  belowOrigin: true, // Displays dropdown below the button
				  constrainWidth:false,
				}
			);
            $('select').material_select();
            $(".button-collapse").sideNav();

            $('#childSettings').tabs();

            $('.info').click(function(e){
                var firstName = e.currentTarget.parentElement.parentElement.children[0].children[0].children[0].children[1].children[0].children[0].value;
                var lastName = e.currentTarget.parentElement.parentElement.children[0].children[0].children[1].children[1].children[0].children[0].value;
                var token = e.currentTarget.parentElement.parentElement.children[0].children[0].children[3].children[1].textContent;

                console.log(first_name + " " + last_name)
                if (!firstName && !lastName){
                    Materialize.toast("Please complete at least one field!", 5000)
                }
                else{
                    $.ajax({
                        type: "PUT",
                        url: '/child/',
                        data: {
                            'fname': firstName,
                            'lname': lastName,
                            'token': token,
                        },
                        dataType: 'json',
                        success: function(response){
                             location.reload();
                        },
                        error: function(response){
                            console.log(response);
                            Materialize.toast("Internal error, please try again later!", 5000)
                        }
                    });
                }
                event.preventDefault();
            });

             $(".picture").click(function(){
                e.preventDefault();
                var formData = new FormData($('#uploadImg')[0]);
            });

            $('.message').click(function(e){
                var token = $(this).attr('token');
                var message = e.currentTarget.parentElement.parentElement.children[2].children[0].value

                if(message == ''){
                    Materialize.toast("Please type a message first!", 5000)
                }else{
                    $.ajax({
                        type: "POST",
                        url: '/rest/message/',
                        data: {
                            csrfmiddlewaretoken: window.CSRF_TOKEN,
                            'token': token,
                            'message': message,
                        },
                        dataType: 'json',
                            success: function(response){
                                 Materialize.toast("Message sent!", 5000)
                            },
                            error: function(response){
                                console.log(response);
                                Materialize.toast("Internal error, please try again later!", 5000)
                            }
                    });
                }
            });

            $('.apps').click(function(e){
                var token = $(this).attr('token');
                var children = e.currentTarget.parentElement.parentElement.children[1].children[1].children;

                var apps = [];

                for (var i = 0; i < children.length; i++) {
                    var tableChild = children[i];
                    var app_name = tableChild.children[0].innerHTML;
                    var status = tableChild.children[1].children[0].children[0].children[0].checked

                    var dict = {};
                    dict["name"] = app_name;

                    if(status){
                        dict["blocked"] = "Y";
                    }else{
                        dict["blocked"] = "N";
                    }
                    apps.push(dict);
                }

                apps = JSON.stringify(apps);

                $.ajax({
                        type: "POST",
                        url: '/rest/apps/',
                        data: {
                            csrfmiddlewaretoken: window.CSRF_TOKEN,
                            'token': token,
                            'apps': apps,
                        },
                        dataType: 'json',
                            success: function(response){
                                 Materialize.toast("Saved!", 3000)
                            },
                            error: function(response){
                                console.log(response);
                                Materialize.toast("Internal error, please try again later!", 5000)
                            }
                    });
            });
		});

    </script>
</head>

<body id="base">
<main>
    <div class="navbar-fixed">
        <nav class="navbar-fixed blue darken-4 main-navigation" role="navigation">
            <div class="nav-wrapper deep-orange">
                <a href="/" class="navbar-brand"><img
                        src="https://i.ibb.co/Jx4V6wJ/1920676965-46d3a9a8-9c60-41e8-bd89-1b0a4ec76940.png"
                        alt="1920676965-46d3a9a8-9c60-41e8-bd89-1b0a4ec76940" border="0" height="95%"></a>
                <ul class="right hide-on-med-and-down">
                    <li><a id="collapse-button">Profile</a></li>
                    <li><a href="/map">Map</a></li>
                    <li><a href="/child">Add child</a></li>
                    <!-- Dropdown Trigger -->
                    <li>
                        <a class="dropdown-button" data-activates="dropdown" data-beloworigin="true">Notifications
                            <i class="material-icons right">arrow_drop_down</i>
                            {% if notifications|length > 0 %}
                            <span class="new badge">{{ notifications|length }}</span>
                            {% endif %}
                        </a>

                    </li>
                    <li><a href="/login">Logout</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <!-- Dropdown Structure -->
    <ul id="dropdown" class="dropdown-content collection">
        {% for notification in notifications %}
        <li class="collection-item avatar">
            <img src="{{ notification.device.child.image.url }}" alt="" class="circle">
            <span id="{{ notification.pk }}" class="title">{{ notification.device.child.first_name }}</span>
            <p id="notification-content" class="{{ notification.pk }}"> {{ notification.description }} </p>
        </li>
        {% endfor %}
        {% if notifications|length == 0 %}
        <li class="collection-item">
            <span class="title">No notifications!</span>
        </li>
        {% endif %}
    </ul>

    <ul id="slide-out" class="side-nav">
        <li>
            <div class="user-view">
                <div class="background">
                    <img src="https://ak2.picdn.net/shutterstock/videos/15526552/thumb/6.jpg">
                </div>
                <a><img class="circle" src="{{ user.image.url }}"></a>
                <a><span class="white-text name">{{ user.first_name }} {{ user.last_name }}</span></a>
                <a><span class="white-text email">{{ user.email }}</span></a>
            </div>
        </li>
        <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
        <li><a href="#!">Second Link</a></li>
        <li>
            <div class="divider"></div>
        </li>
        <li><a class="subheader">Subheader</a></li>
        <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse"></a>

    {% block kids %}
    {% endblock %}

    {% block childForm %}
    {% endblock %}
</main>


<script>
		function readNotification(pk){
			$.ajax({
				type: 'PUT',
				url: '/',
				data: {
					'pk': pk
				}
			});
		}

		function createElement(d,c,t){
            var e = document.createElement(d);
            e.className = c;
            if(t){
            	e.textContent = t;
            }
            return e;
        }

		function checkNotificationNumber(){
			var nextNotification = $(".dropdown-content")[0].firstChild.nextElementSibling;
			if(!nextNotification){
				var notification = createElement("li", "collection-item", null);
				notification.append(createElement("span", "title", "No notifications"));
				$(".dropdown-content").append(notification);
			}
		}

		$("#notification-content").on("click", function(e){
			var pk = $(e.target)[0].className;
			if(pk){
				readNotification(pk);
			}
			$(e.target).parent().remove();
			checkNotificationNumber();
		});

		$(".title").on("click", function(e){
			var pk = $(e.target)[0].id;
			if(pk){
				readNotification(pk);
			}
			$(e.target).parent().remove();
			checkNotificationNumber();
		});

         $('.dropdown-button').on("click", function(){
            $(".new").remove();
        });

        $('#collapse-button').on('click', function(){
            $(".button-collapse").sideNav('show');
        });
</script>


<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>

authentication/templates/authentication/home.html
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

	<link rel="stylesheet" href="{% static 'css/home.css' %}"/>
</head>

<body>
    <a href="{% url 'authentication:login'%}" class="waves-effect waves-light btn">Login</a>
    <a href="{% url 'authentication:register'%}" class="waves-effect waves-light btn">Register</a>
</body>

</html>

authentication/templates/authentication/login.html
{% load static %}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>

    <script>
        $(document).ready(function() {
            M.updateTextFields();
        });
    </script>

    <script>

    </script>
</head>


<body>
<div id="form-page" class="row">
    <div class="col s12 z-depth-6 card-panel hoverable">
        <form class="login-form">
            <div class="row">
                <div class="input-field col s12 center">
                    <img class="logo" src="https://i.ibb.co/WKSyBP8/logo-orange.jpg" class="center">
                </div>
            </div>
            <div class="row margin">
                <div class="input-field col s12">
                    <i class="mdi-social-person-outline prefix"></i>
                    <input name="username" type="text" id="username" class="validate" required="" aria-required="true">
                    <label class="active" for="username">Username</label>
                </div>
            </div>
            <div class="row margin">
                <div class="input-field col s12">
                    <i class="mdi-action-lock-outline prefix"></i>
                    <input name="password" id="password" type="password" class="validate" required="" aria-required="true">
                    <label class="active" for="password">Password</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m12 l12 login-text">
                    <input type="checkbox" id="remember-me"/>
                    <label for="remember-me">Remember me</label>
                </div>
            </div>
            <div class="row">
                <form class="input-field col s12" id="formm" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Login" class="btn col s12 deep-orange" formmethod="post">
                </form>
            </div>
            <div class="row">
                <div class="input-field col s6 m6 l6">
                    <p class="margin medium-small"><a href="/register/">Register Now!</a></p>
                </div>
                <div class="input-field col s6 m6 l6">
                    <p class="margin right-align medium-small"><a href="#">Forgot password?</a></p>
                </div>
            </div>

        </form>
    </div>
</div>
</body>


{% if error %}
<div class="container">
    <h1> {{ error }} </h1>
</div>
{% endif %}

authentication/templates/authentication/profile.html
{% extends "authentication/base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}"/>


<head>

</head>

{% block kids %}

<div class="container">
    <div class="row">

        {% for kid, device, status, apps in grouped %}
        <div class="col s12 m6 l4">
            <div class="card hoverable">
                <div class="card-image"
                     style="background-image:url({{ kid.image.url }}); background-size:cover;background-position:center;">
                    <a class="btn-floating activator halfway-fab waves-effect waves-light red"><i
                            class="material-icons">settings</i></a>
                </div>
                <div class="card-content">
                    <span class="card-title grey-text text-darken-4">{{ kid.first_name }}</span>
                    <p>{{ status }} [{{ device.token}}]</p>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">Settings<i
                            class="material-icons right">close</i></span>
                    <ul class="tabs" id="childSettings">
                        <li class="tab"><a href="#{{ device.token }}_information" class="active">Information</a></li>
                        <li class="tab"><a href="#{{ device.token }}_profile_pic">Profile Image</a></li>
                        <li class="tab"><a href="#{{ device.token }}_message">Chat</a></li>
                        <li class="tab"><a href="#{{ device.token }}_apps">Applications</a></li>
                    </ul>

                    <div id="{{ device.token }}_information">
                        <table class="bordered highlight">
                            <tbody>
                            <tr>
                                <td>First Name</td>
                                <td>
                                    <div class="input-field col s12">
                                        <input id="first_name" type="text" class="validate">
                                        <label for="first_name">{{ kid.first_name }}</label>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Last Name</td>
                                <td>
                                    <div class="input-field col s12">
                                        <input id="last_name" type="text" class="validate">
                                        <label for="last_name">{{ kid.last_name }}</label>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Birthday</td>
                                <td>{{ kid.birth_day }}</td>
                            </tr>
                            <tr>
                                <td>Token</td>
                                <td>{{ device.token }}</td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="input-field col s12 m12">
                            <button class="col s12 waves-effect waves-light btn deep-orange info" id="submit-form"
                                    type="submit">Save
                            </button>
                        </div>
                    </div>

                    <div id="{{ device.token }}_profile_pic">
                        <div class="input-field col l12"></div>
                        <div class="input-field col l12"></div>
                        <div class="input-field col l12"></div>
                        <div class="input-field col l12"></div>
                        <div class="input-field col l12"></div>
                        <div class="input-field col l12"></div>
                        <div class="file-field input-field">

                            <div class="btn deep-orange">
                                <span>Browse</span>
                                <input type="file">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text">
                            </div>
                        </div>
                        <div class="input-field col s12 m12">
                            <button class="col s12 waves-effect waves-light btn deep-orange picture" id="submit_form"
                                    type="submit">Save
                            </button>
                        </div>
                    </div>

                    <div id="{{ device.token }}_message">
                        <ul class="collection" id="{{ device.token }}_history"></ul>
                        <script  type="text/javascript">
                        var i = 0;
                        reloadMessages('{{ device.token }}');

                        function reloadMessages(token){
                            i = i+1;
                            console.log(i);
                            $.ajax({
                                type: "GET",
                                url: "rest/message/",
                                data: {
                                    'token': token
                                },
                                success: function (data) {
                                    var history = document.getElementById(token+'_history');
                                    history.innerHTML = '';
                                    if (data['messages'].length == 0 ) {
                                        header = document.createElement('li');
                                        header.className = 'collection-item';
                                        header.innerHTML = 'No messages sent!'
                                        document.getElementById(token+'_history').appendChild(header);
                                    }
                                    data['messages'].forEach(function(message){
                                        console.log(message);
                                        var node = document.createElement('li');
                                        node.className = 'collection-item';
                                        node.innerHTML = message['message'];

                                        var secondaryContent = document.createElement('li');
                                        secondaryContent.className = 'secondary-content';
                                        node.appendChild(secondaryContent);

                                        if(message['sent'] == true && message['read'] == false){
                                            var icon = document.createElement('i');
                                            icon.className = 'material-icons';
                                            icon.innerHTML = 'done';
                                            secondaryContent.appendChild(icon);
                                        }
                                        else if(message['read'] == true){
                                            var icon = document.createElement('i');
                                            icon.className = 'material-icons';
                                            icon.innerHTML = 'done_all';
                                            secondaryContent.appendChild(icon);
                                        }
                                        history.appendChild(node);
                                });
                                },
                                complete: function(data){
                                    setTimeout(reloadMessages(token), 1000);
                                }
                            });
                         };


                         </script>
                        <div class="input-field col l12">
                            <textarea id="message_text" class="materialize-textarea" data-length="300"></textarea>
                            <label for="message_text">Message</label>
                        </div>
                        <div class="input-field col s12 m12">
                            <button token="{{ device.token }}" class="col s12 waves-effect waves-light btn deep-orange message"
                                    id="send_message" type="submit">Send
                            </button>
                        </div>





                    </div>

                    <div id="{{ device.token }}_apps">
                        <table class="bordered highlight">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Blocked</th>
                            </tr>
                            </thead>
                            <tbody id="apps_status">
                            {% for app in apps %}
                            <tr>
                                <td>{{ app.name }}</td>
                                {% if app.blocked == 'Y' %}
                                <td>
                                    <div class="switch"><label><input type="checkbox" checked>
                                        <span class="lever"></span></label></div>
                                </td>
                                {% else %}
                                <td>
                                    <div class="switch"><label><input type="checkbox">
                                        <span class="lever"></span></label></div>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                            </tbody>

                            <div class="input-field col s12 m12">
                                <button token="{{ device.token }}"
                                        class="col s12 waves-effect waves-light btn deep-orange apps"
                                        id="save_blocked_apps" type="submit">Save
                                </button>
                            </div>
                        </table>

                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}